name: recebimento_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  flutter_zxing: ^1.5.0
  cupertino_icons: ^1.0.6
  sqflite: ^2.3.0
  path: ^1.9.0
  connectivity_plus: ^6.0.3 # Para detectar se há internet
  pdf: ^3.10.8
  printing: ^5.12.0
  path_provider: ^2.1.2
  share_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icone.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icone.png"


flutter:
  uses-material-design: true
  assets:
    - assets/logo.png