name: recebimento_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  mobile_scanner: ^5.1.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icone.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icone.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/icone.png" # Usando o ícone quadrado
  android_gravity: center
  
  # Força o branco no modo escuro
  color_dark: "#FFFFFF"
  image_dark: "assets/icone.png"
  
  # Configuração específica para Android 12+
  android_12:
    image: "assets/icone.png"
    color: "#FFFFFF"
    icon_background_color: "#FFFFFF"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png